name: Flat
on:
  schedule:
    - cron: 31 9 * * 1-5
  workflow_dispatch: 
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
      - ./postprocess.py
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
      - name: Fetch data
        uses: githubocto/flat@cea5ee43fce40ef71501bf5724a00d45db11641d # v3
        with:
          http_url: http://environment.data.gov.uk/flood-monitoring/id/stations/E12580/readings.json?_limit=100&_sorted&parameter=rainfall
          downloaded_filename: rainfall.json
          postprocess: ./postprocess.ts
