name: Flat
on:
  schedule:
    - cron: 31 9 * * 1-5
  workflow_dispatch: 
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
      - ./postprocess.py
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://environment.data.gov.uk/flood-monitoring/id/stations/E12580/readings.json?_limit=100&_sorted&parameter=rainfall
          downloaded_filename: rainfall.json
          postprocess: ./postprocess.ts
